#!/bin/zsh
function bak() { # Crée une archive tar de chaque fichier passé en  paramètre
	date=$(date "+%Y-%m-%d_%H-%M-%S")

    extension=''
    if [[ "$1" == '-c' ]] || [[ "$1" == '--compress' ]]; then
        extension='.gz'
        shift
    fi

	for file in $*; do
		tar -acvf "${file#/}_$date.tar${extension}" ${file}
	done
}

# vim: foldmethod=syntax
