#!/usr/bin/zsh

mktest() {
    usage='usage: mktest [directory-name]\n'

    if (( ARGC > 1 )); then
		print $usage
        return 1
    fi

    case $ARGC in
        0)

            directory="/tmp/test"
            ;;
        1)
            directory="/tmp/$1"
            ;;
        *)
            print $usage
            return 1
            ;;
    esac

    mkdir -p $directory
    builtin cd $directory
}

