#!/bin/zsh

pacsearch() {
	if [[ -e /usr/bin/yaourt ]]; then
		yaourt -Ss $@ --color | less -RF

	elif [[ -e /usr/bin/pikaur ]]; then
		pikaur --color=always -Ss $@ | less -RF

	else
		pacman --color=always -Ss $@ | less -RF

	fi
}
