#!/bin/zsh

pacsearch() {
	if [[ -e /usr/bin/yay ]]; then
		yay -Ss $@ --color=always | less -RF

	elif [[ -e /usr/bin/pikaur ]]; then
		pikaur --color=always -Ss $@ | less -RF

	else
		pacman --color=always -Ss $@ | less -RF

	fi
}
