#!/usr/bin/env zsh

pkgcache() {
    usage() {
        echo "Usage: ${0} (-c|--clean)"
        echo "Clear package cache"
    }

    if [[ $1 != '-c' ]] && [[ $1 != '--clean' ]]; then
        usage
        return 1
    fi

    paccache -rk3
    paccache -ruk0

    du -sh $cache_directory
}
