#!/bin/zsh
upgrade() { # Met à jour un système Archlinux
	if [[ $USER != 'root' ]]; then
		su -c 'source $HOME/.zshenv && source $ZDOTDIR/zshrc && upgrade -c' -l
		return 0
	fi

	log_file='/var/log/last_upgrade.log'
	if [[ -e $log_file ]]; then
		echo -n "Dernière mise à jour: "
		cat $log_file
	fi
		
	complete=false
	pacman -Syu && complete=true
	if [[ $complete == true ]]; then
		date > $log_file
		chmod o+r $log_file
	fi
		
	pacdiff

	echo "\n"
    pkgcache --clean
}

# vim: foldmethod=syntax
